#database info configuration
spring:
  datasource:
  url: jdbc:mysql://localhost:3306/rbac
  driver-class-name: com.mysql.cj.jdbc.Driver
  username: root
  password: 123456

#log level configuration
logging:
  level:
  root: info #set root log level as info
  com.yuewang: debug #set log under com.yuewang's level as debug